### PR TITLE
[Bug] Hero & Other Headers Bg

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

- Update hero background with the one provided [here](https://trello.com/c/KsHxLqEg/54-home-hero-banner-bg-img-looks-pixelated) 
- Fix background colours on hero map ([issue](https://trello.com/c/ywAP7Brz/55-home-hero-map-has-a-white-background))
- Add  favicon

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Just had a quick look at `at-mtKenya-1_alt@2400x.jpeg` and it's around 600x300. This can't be a high quality image @KhadijaMahanga

**Comment by KhadijaMahanga** [comment]
> Just had a quick look at `sat-mtKenya-1_alt@2400x.jpeg` and it's around 600x300. This can't be a high quality image @KhadijaMahanga

@kilemensi Okay, let me confirm with Piero. I am using what he attached to this [stories](https://trello.com/c/CPUUXX4a/56-home-how-it-works-banner-bg-img-looks-pixelated)

**Comment by KhadijaMahanga** [comment]
@kilemensi but they seem different. Its is 2400 x 1212 [here](https://trello.com/1/cards/61f29bd69b210a452ceab429/attachments/61f29d549c33a86a830aa493/download/sat-mtKenya-1_alt%402400x.jpg) Let me investigate how we are using it with next`Image`

**Comment by kilemensi** [comment]
> @kilemensi but they seem different. Its is 2400 x 1212 [here](https://trello.com/1/cards/61f29bd69b210a452ceab429/attachments/61f29d549c33a86a830aa493/download/sat-mtKenya-1_alt%402400x.jpg) Let me investigate how we are using it with next`Image`

Yes @KhadijaMahanga  I just clicked the image shared by Piero and it's huge i.e. really high quality

**Comment by KhadijaMahanga** [comment]
@kilemensi the same image on my local is `1920 by 970` It must be vercel

**Comment by kilemensi** [comment]
> @kilemensi the same image on my local is `1920 by 970` It must be vercel

This is before getting to Vercel @KhadijaMahanga .

1. File that Piero shared is 4MB, 2400x1212, extensions `.jpg`,
2. File in your local machine is 1920x970, don't know the extension but something must have scaled it down, and lastly
3. File on this [PR](https://github.com/CodeForAfrica/PesaYetu/blob/9d806a2446b85222e6a58136718a5d7787ef19c1/src/assets/images/sat-mtKenya-1_alt%402400x.jpeg) (i.e. on GitHub and not Vercel) is 230KB, 600x303, extension `.jpeg`

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
