### PR TITLE
Add About Hero

### PR DESCRIPTION
**Pull request by KobbyMmo**
## Description

Add about page and hero specified by task [179117123](https://www.pivotaltracker.com/story/show/179117123)

Fixes # ([179117123](https://www.pivotaltracker.com/story/show/179117123))

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots
image

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by gertie-sheshe — COMMENTED** [review]
Great work @KobbyMmo A few comments:

1. `ABOUT` text should be 14px and a margin bottom of `13px` Currently, it is 16px and without a margin/padding.
Screenshot 2021-08-06 at 09 49 36

2. Description text font is different, with `40px` margin bottom, looks like it should be less than that?
Screenshot 2021-08-06 at 09 52 26

**Review by KhadijaMahanga — COMMENTED** [review]
@KobbyMmo looks good.

But for tablet, it looks a bit off (the white background is not centered ) as how it is on desktop & mobile
Screenshot from 2021-08-09 14-43-38
What total height are you using for tablet?

**Review by nerdlet — APPROVED** [review]
🚀 🚀

**Review by KhadijaMahanga — APPROVED** [review]

**Comment by KhadijaMahanga** [comment]
@KobbyMmo lets resolve conflict before merging

**Pull request merged**
