### PR TITLE
[Chore] Merry-go-round

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

Reduce usage of Carousel down to single component.

## Type of change

- [x] Chore

## Screenshots

Screenshot 2021-09-03 at 15-15-31 PesaYetu

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by KhadijaMahanga — APPROVED** [review]
🚀 🚀 Looks Good.

We need to customize the dots for `About Team` component. Slightly different in color

**Review by KobbyMmo — APPROVED** [review]
less code is good @kilemensi  🚀 

Unrelated to your PR, but once you are touching carousels, maybe you can fix it as well. There has to be a margin down there
image
image

**Comment by kilemensi** [comment]
> less code is good @kilemensi rocket
> 
> Unrelated to your PR, but once you are touching carousels, maybe you can fix ...

Look at you. LOOK AT YOU!!!

**Review by nerdlet — APPROVED** [review]
Looks good 🚀

**Pull request merged**
