### PR TITLE
[Chore] Line time series + sorting ordinals

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

- Time series
- Sorting ordinals

Screenshot 2022-03-29 at 10 10 30

## Type of change

- [x] Chore

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽

_____


1. What’s up with robots.txt and site map?
2. All the 12 months on x-axis won’t fit in mobile screens.

**Comment by KhadijaMahanga** [comment]
@kilemensi 
1. it just showed on my local, not sure why? But shouldn't be committed on this PR.
2. let me change the time format to numbers so it will fit on mobiles

**Comment by KhadijaMahanga** [comment]
> > 2. let me change the time format to numbers so it will fit on mobiles
> 
> Has this been done @KhadijaMahanga ?

@kilemensi yes! So for this one I realised we can't have `one-format-fits-all`  for all time scale. For instance, a time unit can be only months, or data-month, or data-month-year. So we rather have format option from backend (chart configuration).

**Comment by kilemensi** [comment]
> > > 2. let me change the time format to numbers so it will fit on mobiles
> > 
> > 
> > Has this been done @KhadijaMahanga ?
> 
> @kilemensi yes! So for this one I realised we can't have `one-format-fits-all` for all time scale. For instance, a time unit can be only months, or data-month, or data-month-year. So we rather have format option from backend (chart configuration).

So it means for this one it will just show Jan, Feb, etc., in both desktop and mobile (at least for now). Correct @KhadijaMahanga ?

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
