### PR TITLE
[Fix] Our Partners

### PR DESCRIPTION
**Pull request by kilemensi**
## Description

 - [x] Our Partners,
 - [x] Project Owner, and
 - [x] Newsletter. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots

T1

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by KhadijaMahanga — APPROVED** [review]

**Review by KobbyMmo — COMMENTED** [review]
I don't know if the effect is intentional, but the Project Owner and Newsletter don't seem to fit in the container/section as the page gets bigger.

image

**Comment by kilemensi** [comment]
> I don't know if the effect is intentional, but the Project Owner and...
>

Of course it's by design @KobbyMmo . They already don't fit in the Section even in the XD.
Screenshot 2021-08-19 at 09-57-34 PesaYetu - web DEV

**Review by BrendaBucha — APPROVED** [review]
Looks good  🚀  🚀

**Review by KobbyMmo — APPROVED** [review]
🚀 🎸 🇹🇿 💯 @kilemensi

**Pull request merged**
