### PR TITLE
[Bugs] Fix donut tooltip label + treemap label

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description
- Donut chart tooltip was showing percentage no matter the `defaultType` config. This PR shows tooltip value depending on the defaultType provided.
- We are also setting `limit` property to Treemap text to limit overflowing of labels instead on hiding them depending on average

Fixes # (issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by kilemensi — APPROVED** [review]
🚀 🚀 

----

Looks dope, especially the Treemap with limited labels.

PS: Don't line charts have any sort of tooltip?

**Comment by KhadijaMahanga** [comment]
> PS: Don't line charts have any sort of tooltip?

@kilemensi line charts have tooltip

**Comment by kilemensi** [comment]
> > PS: Don't line charts have any sort of tooltip?
> 
> @kilemensi line charts have tooltip

Ohh... at the exact x,y points... Cool, cool @KhadijaMahanga . But the cursor is different from other charts though.

**Comment by KhadijaMahanga** [comment]
> 
> Ohh... at the exact x,y data points... Cool, cool @KhadijaMahanga . But the cursor is different from other charts though.
Screenshot 2022-01-31 at 12 09 41
@kilemensi this is from design, or should we be showing both cursor and the circle symbol

**Comment by kilemensi** [comment]
Nah, I think normal cursor works well here actually @KhadijaMahanga  (the circle won't be easy to spot since on line chart, most of the chart is just background i.e. white).

**Pull request merged**
