### PR TITLE
[Fix] Sorting donut chart + axis ticks count

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description
- Sort donut chart in descending order
- Update `tickCount` for chart with scale value less than ticks count
- Add key to stories tab

Fixes # (issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### Bug
https://user-images.githubusercontent.com/7962097/156136389-db6d790d-735d-475f-ac63-9d8ac9985bd3.mov

Screenshot 2022-03-01 at 11 53 31

### Fix
https://user-images.githubusercontent.com/7962097/156136508-ba216953-c6e2-469b-9fa1-8a1252bae081.mov

Screenshot 2022-03-01 at 11 59 09

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
QQ @KhadijaMahanga, is sorting based on values applicable to `Donut` charts only or to even 👇🏽 

Screenshot from 2022-03-01 12-09-24

**Comment by kilemensi** [comment]
> QQ @KhadijaMahanga, is sorting based on values applicable to `Donut` charts only or to even 👇🏽
> 
> Screenshot from 2022-03-01 12-09-24


Or should this chart be converted to a Donut chart even?

**Review by kilemensi — APPROVED** [review]
🚀

**Review by nerdlet — APPROVED** [review]
Looks good  @KhadijaMahanga 🚀 🚀

**Pull request merged**
