### PR TITLE
[Bug] Fix Treeview item onClick

### PR DESCRIPTION
**Pull request by KhadijaMahanga**
## Description

- TreeView links not working as expected due to conflict, by having onClick method and link href on the same element. This PR fixes that

Fixes # (issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
👋🏽 @KhadijaMahanga ... For me, Treemap seem to work fine on <https://pesayetu.dev.codeforafrica.org/explore/6> or am I looking at the wrong Treemap?

Peek 2022-02-04 08-59

**Comment by KhadijaMahanga** [comment]
> 👋🏽 @KhadijaMahanga ... For me, Treemap seem to work fine on https://pesayetu.dev.codeforafrica.org/explore/6 or am I looking at the wrong Treemap?
> 
@kilemensi weird.. I also tested on firefox it works, but it does not work on chrome

**Comment by kilemensi** [comment]
> @kilemensi weird.. I also tested on firefox it works, but it does not work on chrome

This could be a [Chrome-specific](https://caniuse.com/?search=scroll-behavior) bug @KhadijaMahanga

**Comment by KhadijaMahanga** [comment]
[PR](https://github.com/CodeForAfrica/PesaYetu/pull/166)
 addresses this

**Pull request closed without merging**
